name: schedule
on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Commit Setup
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"

      - run: npm install
      - run: npm run start

      - name: Check pair.json array length
        run: |
          jq -e 'length > 0' pair.json || (echo "Error: pair.json array is empty" && exit 1)

      - name: Commit results
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add .
            git commit -m "Update pair"
            git push origin main
          fi
